version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: loyalty_tier
        data_tests:
          - not_null
          - accepted_values:
              values:
                - Bronze
                - Silver
                - Gold

  - name: stg_products
    columns:
      - name: product_id
        data_tests:
          - not_null
          - unique
      - name: product_name
        data_tests:
          - not_null
      - name: price
        data_tests:
          - not_null
      - name: category
        data_tests:
          - not_null
          - accepted_values:
              values:
                - Television
                - Laptop
                - Smartphone
                - Headphones
                - Camera
                - Smartwatch
                - Tablet
                - Printer
                - Monitor
                - Speaker

  - name: stg_orders
    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique
      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: product_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        data_tests:
          - not_null
      - name: order_date
        data_tests:
          - not_null
      - name: delivery_date
        data_tests:
          - not_null
      - name: status
        data_tests:
          - not_null
          - accepted_values:
              values:
                - pending
                - shipped
                - delivered
                - cancelled